// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: RustPlusContracts.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace RustPlusContracts
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Vector2 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"x")]
        public float X
        {
            get => __pbn__X.GetValueOrDefault();
            set => __pbn__X = value;
        }
        public bool ShouldSerializeX() => __pbn__X != null;
        public void ResetX() => __pbn__X = null;
        private float? __pbn__X;

        [global::ProtoBuf.ProtoMember(2, Name = @"y")]
        public float Y
        {
            get => __pbn__Y.GetValueOrDefault();
            set => __pbn__Y = value;
        }
        public bool ShouldSerializeY() => __pbn__Y != null;
        public void ResetY() => __pbn__Y = null;
        private float? __pbn__Y;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Vector3 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"x")]
        public float X
        {
            get => __pbn__X.GetValueOrDefault();
            set => __pbn__X = value;
        }
        public bool ShouldSerializeX() => __pbn__X != null;
        public void ResetX() => __pbn__X = null;
        private float? __pbn__X;

        [global::ProtoBuf.ProtoMember(2, Name = @"y")]
        public float Y
        {
            get => __pbn__Y.GetValueOrDefault();
            set => __pbn__Y = value;
        }
        public bool ShouldSerializeY() => __pbn__Y != null;
        public void ResetY() => __pbn__Y = null;
        private float? __pbn__Y;

        [global::ProtoBuf.ProtoMember(3, Name = @"z")]
        public float Z
        {
            get => __pbn__Z.GetValueOrDefault();
            set => __pbn__Z = value;
        }
        public bool ShouldSerializeZ() => __pbn__Z != null;
        public void ResetZ() => __pbn__Z = null;
        private float? __pbn__Z;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Vector4 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"x")]
        public float X
        {
            get => __pbn__X.GetValueOrDefault();
            set => __pbn__X = value;
        }
        public bool ShouldSerializeX() => __pbn__X != null;
        public void ResetX() => __pbn__X = null;
        private float? __pbn__X;

        [global::ProtoBuf.ProtoMember(2, Name = @"y")]
        public float Y
        {
            get => __pbn__Y.GetValueOrDefault();
            set => __pbn__Y = value;
        }
        public bool ShouldSerializeY() => __pbn__Y != null;
        public void ResetY() => __pbn__Y = null;
        private float? __pbn__Y;

        [global::ProtoBuf.ProtoMember(3, Name = @"z")]
        public float Z
        {
            get => __pbn__Z.GetValueOrDefault();
            set => __pbn__Z = value;
        }
        public bool ShouldSerializeZ() => __pbn__Z != null;
        public void ResetZ() => __pbn__Z = null;
        private float? __pbn__Z;

        [global::ProtoBuf.ProtoMember(4, Name = @"w")]
        public float W
        {
            get => __pbn__W.GetValueOrDefault();
            set => __pbn__W = value;
        }
        public bool ShouldSerializeW() => __pbn__W != null;
        public void ResetW() => __pbn__W = null;
        private float? __pbn__W;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Half3 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"x")]
        public float X
        {
            get => __pbn__X.GetValueOrDefault();
            set => __pbn__X = value;
        }
        public bool ShouldSerializeX() => __pbn__X != null;
        public void ResetX() => __pbn__X = null;
        private float? __pbn__X;

        [global::ProtoBuf.ProtoMember(2, Name = @"y")]
        public float Y
        {
            get => __pbn__Y.GetValueOrDefault();
            set => __pbn__Y = value;
        }
        public bool ShouldSerializeY() => __pbn__Y != null;
        public void ResetY() => __pbn__Y = null;
        private float? __pbn__Y;

        [global::ProtoBuf.ProtoMember(3, Name = @"z")]
        public float Z
        {
            get => __pbn__Z.GetValueOrDefault();
            set => __pbn__Z = value;
        }
        public bool ShouldSerializeZ() => __pbn__Z != null;
        public void ResetZ() => __pbn__Z = null;
        private float? __pbn__Z;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Color : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"r")]
        public float R
        {
            get => __pbn__R.GetValueOrDefault();
            set => __pbn__R = value;
        }
        public bool ShouldSerializeR() => __pbn__R != null;
        public void ResetR() => __pbn__R = null;
        private float? __pbn__R;

        [global::ProtoBuf.ProtoMember(2, Name = @"g")]
        public float G
        {
            get => __pbn__G.GetValueOrDefault();
            set => __pbn__G = value;
        }
        public bool ShouldSerializeG() => __pbn__G != null;
        public void ResetG() => __pbn__G = null;
        private float? __pbn__G;

        [global::ProtoBuf.ProtoMember(3, Name = @"b")]
        public float B
        {
            get => __pbn__B.GetValueOrDefault();
            set => __pbn__B = value;
        }
        public bool ShouldSerializeB() => __pbn__B != null;
        public void ResetB() => __pbn__B = null;
        private float? __pbn__B;

        [global::ProtoBuf.ProtoMember(4, Name = @"a")]
        public float A
        {
            get => __pbn__A.GetValueOrDefault();
            set => __pbn__A = value;
        }
        public bool ShouldSerializeA() => __pbn__A != null;
        public void ResetA() => __pbn__A = null;
        private float? __pbn__A;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Ray : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"origin")]
        public Vector3 Origin { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"direction")]
        public Vector3 Direction { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClanActionResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"request_id", IsRequired = true)]
        public int RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"result", IsRequired = true)]
        public int Result { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"has_clan_info", IsRequired = true)]
        public bool HasClanInfo { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"clan_info")]
        public ClanInfo ClanInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClanInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"clan_id", IsRequired = true)]
        public long ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"created", IsRequired = true)]
        public long Created { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"creator", IsRequired = true)]
        public ulong Creator { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"motd")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Motd
        {
            get => __pbn__Motd ?? "";
            set => __pbn__Motd = value;
        }
        public bool ShouldSerializeMotd() => __pbn__Motd != null;
        public void ResetMotd() => __pbn__Motd = null;
        private string __pbn__Motd;

        [global::ProtoBuf.ProtoMember(6, Name = @"motd_timestamp")]
        public long MotdTimestamp
        {
            get => __pbn__MotdTimestamp.GetValueOrDefault();
            set => __pbn__MotdTimestamp = value;
        }
        public bool ShouldSerializeMotdTimestamp() => __pbn__MotdTimestamp != null;
        public void ResetMotdTimestamp() => __pbn__MotdTimestamp = null;
        private long? __pbn__MotdTimestamp;

        [global::ProtoBuf.ProtoMember(7, Name = @"motd_author")]
        public ulong MotdAuthor
        {
            get => __pbn__MotdAuthor.GetValueOrDefault();
            set => __pbn__MotdAuthor = value;
        }
        public bool ShouldSerializeMotdAuthor() => __pbn__MotdAuthor != null;
        public void ResetMotdAuthor() => __pbn__MotdAuthor = null;
        private ulong? __pbn__MotdAuthor;

        [global::ProtoBuf.ProtoMember(8, Name = @"logo")]
        public byte[] Logo
        {
            get => __pbn__Logo;
            set => __pbn__Logo = value;
        }
        public bool ShouldSerializeLogo() => __pbn__Logo != null;
        public void ResetLogo() => __pbn__Logo = null;
        private byte[] __pbn__Logo;

        [global::ProtoBuf.ProtoMember(9, Name = @"color", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Color
        {
            get => __pbn__Color.GetValueOrDefault();
            set => __pbn__Color = value;
        }
        public bool ShouldSerializeColor() => __pbn__Color != null;
        public void ResetColor() => __pbn__Color = null;
        private int? __pbn__Color;

        [global::ProtoBuf.ProtoMember(10, Name = @"roles")]
        public global::System.Collections.Generic.List<Role> Roles { get; } = new global::System.Collections.Generic.List<Role>();

        [global::ProtoBuf.ProtoMember(11, Name = @"members")]
        public global::System.Collections.Generic.List<Member> Members { get; } = new global::System.Collections.Generic.List<Member>();

        [global::ProtoBuf.ProtoMember(12, Name = @"invites")]
        public global::System.Collections.Generic.List<Invite> Invites { get; } = new global::System.Collections.Generic.List<Invite>();

        [global::ProtoBuf.ProtoMember(13, Name = @"max_member_count")]
        public int MaxMemberCount
        {
            get => __pbn__MaxMemberCount.GetValueOrDefault();
            set => __pbn__MaxMemberCount = value;
        }
        public bool ShouldSerializeMaxMemberCount() => __pbn__MaxMemberCount != null;
        public void ResetMaxMemberCount() => __pbn__MaxMemberCount = null;
        private int? __pbn__MaxMemberCount;

        [global::ProtoBuf.ProtoContract()]
        public partial class Role : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"role_id", IsRequired = true)]
            public int RoleId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"rank", IsRequired = true)]
            public int Rank { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"name", IsRequired = true)]
            public string Name { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"can_set_motd", IsRequired = true)]
            public bool CanSetMotd { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"can_set_logo", IsRequired = true)]
            public bool CanSetLogo { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"can_invite", IsRequired = true)]
            public bool CanInvite { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"can_kick", IsRequired = true)]
            public bool CanKick { get; set; }

            [global::ProtoBuf.ProtoMember(8, Name = @"can_promote", IsRequired = true)]
            public bool CanPromote { get; set; }

            [global::ProtoBuf.ProtoMember(9, Name = @"can_demote", IsRequired = true)]
            public bool CanDemote { get; set; }

            [global::ProtoBuf.ProtoMember(10, Name = @"can_set_player_notes", IsRequired = true)]
            public bool CanSetPlayerNotes { get; set; }

            [global::ProtoBuf.ProtoMember(11, Name = @"can_access_logs", IsRequired = true)]
            public bool CanAccessLogs { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Member : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"steam_id", IsRequired = true)]
            public ulong SteamId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"role_id", IsRequired = true)]
            public int RoleId { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"joined", IsRequired = true)]
            public long Joined { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"last_seen", IsRequired = true)]
            public long LastSeen { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"notes")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Notes
            {
                get => __pbn__Notes ?? "";
                set => __pbn__Notes = value;
            }
            public bool ShouldSerializeNotes() => __pbn__Notes != null;
            public void ResetNotes() => __pbn__Notes = null;
            private string __pbn__Notes;

            [global::ProtoBuf.ProtoMember(6, Name = @"online")]
            public bool Online
            {
                get => __pbn__Online.GetValueOrDefault();
                set => __pbn__Online = value;
            }
            public bool ShouldSerializeOnline() => __pbn__Online != null;
            public void ResetOnline() => __pbn__Online = null;
            private bool? __pbn__Online;

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Invite : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"steam_id", IsRequired = true)]
            public ulong SteamId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"recruiter", IsRequired = true)]
            public ulong Recruiter { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"timestamp", IsRequired = true)]
            public long Timestamp { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClanLog : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"clan_id", IsRequired = true)]
        public long ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"log_entries")]
        public global::System.Collections.Generic.List<Entry> LogEntries { get; } = new global::System.Collections.Generic.List<Entry>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Entry : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"timestamp", IsRequired = true)]
            public long Timestamp { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"event_key", IsRequired = true)]
            public string EventKey { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"arg1")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Arg1
            {
                get => __pbn__Arg1 ?? "";
                set => __pbn__Arg1 = value;
            }
            public bool ShouldSerializeArg1() => __pbn__Arg1 != null;
            public void ResetArg1() => __pbn__Arg1 = null;
            private string __pbn__Arg1;

            [global::ProtoBuf.ProtoMember(4, Name = @"arg2")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Arg2
            {
                get => __pbn__Arg2 ?? "";
                set => __pbn__Arg2 = value;
            }
            public bool ShouldSerializeArg2() => __pbn__Arg2 != null;
            public void ResetArg2() => __pbn__Arg2 = null;
            private string __pbn__Arg2;

            [global::ProtoBuf.ProtoMember(5, Name = @"arg3")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Arg3
            {
                get => __pbn__Arg3 ?? "";
                set => __pbn__Arg3 = value;
            }
            public bool ShouldSerializeArg3() => __pbn__Arg3 != null;
            public void ResetArg3() => __pbn__Arg3 = null;
            private string __pbn__Arg3;

            [global::ProtoBuf.ProtoMember(6, Name = @"arg4")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Arg4
            {
                get => __pbn__Arg4 ?? "";
                set => __pbn__Arg4 = value;
            }
            public bool ShouldSerializeArg4() => __pbn__Arg4 != null;
            public void ResetArg4() => __pbn__Arg4 = null;
            private string __pbn__Arg4;

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClanInvitations : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"invitations")]
        public global::System.Collections.Generic.List<Invitation> Invitations { get; } = new global::System.Collections.Generic.List<Invitation>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Invitation : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"clan_id", IsRequired = true)]
            public long ClanId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"recruiter", IsRequired = true)]
            public ulong Recruiter { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"timestamp", IsRequired = true)]
            public long Timestamp { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"seq", IsRequired = true)]
        public uint Seq { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"player_id", IsRequired = true)]
        public ulong PlayerId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"player_token", IsRequired = true)]
        public int PlayerToken { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"entity_id")]
        public uint EntityId
        {
            get => __pbn__EntityId.GetValueOrDefault();
            set => __pbn__EntityId = value;
        }
        public bool ShouldSerializeEntityId() => __pbn__EntityId != null;
        public void ResetEntityId() => __pbn__EntityId = null;
        private uint? __pbn__EntityId;

        [global::ProtoBuf.ProtoMember(8, Name = @"get_info")]
        public AppEmpty GetInfo { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"get_time")]
        public AppEmpty GetTime { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"get_map")]
        public AppEmpty GetMap { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"get_team_info")]
        public AppEmpty GetTeamInfo { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"get_team_chat")]
        public AppEmpty GetTeamChat { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"send_team_message")]
        public AppSendMessage SendTeamMessage { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"get_entity_info")]
        public AppEmpty GetEntityInfo { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"set_entity_value")]
        public AppSetEntityValue SetEntityValue { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"check_subscription")]
        public AppEmpty CheckSubscription { get; set; }

        [global::ProtoBuf.ProtoMember(17, Name = @"set_subscription")]
        public AppFlag SetSubscription { get; set; }

        [global::ProtoBuf.ProtoMember(18, Name = @"get_map_markers")]
        public AppEmpty GetMapMarkers { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"promote_to_leader")]
        public AppPromoteToLeader PromoteToLeader { get; set; }

        [global::ProtoBuf.ProtoMember(21, Name = @"get_clan_info")]
        public AppEmpty GetClanInfo { get; set; }

        [global::ProtoBuf.ProtoMember(22, Name = @"set_clan_motd")]
        public AppSendMessage SetClanMotd { get; set; }

        [global::ProtoBuf.ProtoMember(23, Name = @"get_clan_chat")]
        public AppEmpty GetClanChat { get; set; }

        [global::ProtoBuf.ProtoMember(24, Name = @"send_clan_message")]
        public AppSendMessage SendClanMessage { get; set; }

        [global::ProtoBuf.ProtoMember(25, Name = @"get_nexus_auth")]
        public AppGetNexusAuth GetNexusAuth { get; set; }

        [global::ProtoBuf.ProtoMember(30, Name = @"camera_subscribe")]
        public AppCameraSubscribe CameraSubscribe { get; set; }

        [global::ProtoBuf.ProtoMember(31, Name = @"camera_unsubscribe")]
        public AppEmpty CameraUnsubscribe { get; set; }

        [global::ProtoBuf.ProtoMember(32, Name = @"camera_input")]
        public AppCameraInput CameraInput { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"response")]
        public AppResponse Response { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"broadcast")]
        public AppBroadcast Broadcast { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"seq", IsRequired = true)]
        public uint Seq { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"success")]
        public AppSuccess Success { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"error")]
        public AppError Error { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"info")]
        public AppInfo Info { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"time")]
        public AppTime Time { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"map")]
        public AppMap Map { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"team_info")]
        public AppTeamInfo TeamInfo { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"team_chat")]
        public AppTeamChat TeamChat { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"entity_info")]
        public AppEntityInfo EntityInfo { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"flag")]
        public AppFlag Flag { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"map_markers")]
        public AppMapMarkers MapMarkers { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"clan_info")]
        public AppClanInfo ClanInfo { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"clan_chat")]
        public AppClanChat ClanChat { get; set; }

        [global::ProtoBuf.ProtoMember(17, Name = @"nexus_auth")]
        public AppNexusAuth NexusAuth { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"camera_subscribe_info")]
        public AppCameraInfo CameraSubscribeInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppBroadcast : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(4, Name = @"team_changed")]
        public AppTeamChanged TeamChanged { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"team_message")]
        public AppNewTeamMessage TeamMessage { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"entity_changed")]
        public AppEntityChanged EntityChanged { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"clan_changed")]
        public AppClanChanged ClanChanged { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"clan_message")]
        public AppNewClanMessage ClanMessage { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"camera_rays")]
        public AppCameraRays CameraRays { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppEmpty : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppSendMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"message", IsRequired = true)]
        public string Message { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppSetEntityValue : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"value", IsRequired = true)]
        public bool Value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppPromoteToLeader : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"steam_id", IsRequired = true)]
        public ulong SteamId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppGetNexusAuth : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"app_key", IsRequired = true)]
        public string AppKey { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppSuccess : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppError : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error", IsRequired = true)]
        public string Error { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppFlag : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"value", IsRequired = true)]
        public bool Value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"header_image", IsRequired = true)]
        public string HeaderImage { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"url", IsRequired = true)]
        public string Url { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"map", IsRequired = true)]
        public string Map { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"map_size", IsRequired = true)]
        public uint MapSize { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"wipe_time", IsRequired = true)]
        public uint WipeTime { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"players", IsRequired = true)]
        public uint Players { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"max_players", IsRequired = true)]
        public uint MaxPlayers { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"queued_players", IsRequired = true)]
        public uint QueuedPlayers { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"seed")]
        public uint Seed
        {
            get => __pbn__Seed.GetValueOrDefault();
            set => __pbn__Seed = value;
        }
        public bool ShouldSerializeSeed() => __pbn__Seed != null;
        public void ResetSeed() => __pbn__Seed = null;
        private uint? __pbn__Seed;

        [global::ProtoBuf.ProtoMember(11, Name = @"salt")]
        public uint Salt
        {
            get => __pbn__Salt.GetValueOrDefault();
            set => __pbn__Salt = value;
        }
        public bool ShouldSerializeSalt() => __pbn__Salt != null;
        public void ResetSalt() => __pbn__Salt = null;
        private uint? __pbn__Salt;

        [global::ProtoBuf.ProtoMember(12, Name = @"logo_image")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LogoImage
        {
            get => __pbn__LogoImage ?? "";
            set => __pbn__LogoImage = value;
        }
        public bool ShouldSerializeLogoImage() => __pbn__LogoImage != null;
        public void ResetLogoImage() => __pbn__LogoImage = null;
        private string __pbn__LogoImage;

        [global::ProtoBuf.ProtoMember(13, Name = @"nexus")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Nexus
        {
            get => __pbn__Nexus ?? "";
            set => __pbn__Nexus = value;
        }
        public bool ShouldSerializeNexus() => __pbn__Nexus != null;
        public void ResetNexus() => __pbn__Nexus = null;
        private string __pbn__Nexus;

        [global::ProtoBuf.ProtoMember(14, Name = @"nexus_id")]
        public int NexusId
        {
            get => __pbn__NexusId.GetValueOrDefault();
            set => __pbn__NexusId = value;
        }
        public bool ShouldSerializeNexusId() => __pbn__NexusId != null;
        public void ResetNexusId() => __pbn__NexusId = null;
        private int? __pbn__NexusId;

        [global::ProtoBuf.ProtoMember(15, Name = @"nexus_zone")]
        [global::System.ComponentModel.DefaultValue("")]
        public string NexusZone
        {
            get => __pbn__NexusZone ?? "";
            set => __pbn__NexusZone = value;
        }
        public bool ShouldSerializeNexusZone() => __pbn__NexusZone != null;
        public void ResetNexusZone() => __pbn__NexusZone = null;
        private string __pbn__NexusZone;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppTime : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"day_length_minutes", IsRequired = true)]
        public float DayLengthMinutes { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"time_scale", IsRequired = true)]
        public float TimeScale { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"sunrise", IsRequired = true)]
        public float Sunrise { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"sunset", IsRequired = true)]
        public float Sunset { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"time", IsRequired = true)]
        public float Time { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppMap : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"width", IsRequired = true)]
        public uint Width { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"height", IsRequired = true)]
        public uint Height { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"jpg_image", IsRequired = true)]
        public byte[] JpgImage { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"ocean_margin", IsRequired = true)]
        public int OceanMargin { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"monuments")]
        public global::System.Collections.Generic.List<Monument> Monuments { get; } = new global::System.Collections.Generic.List<Monument>();

        [global::ProtoBuf.ProtoMember(6, Name = @"background")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Background
        {
            get => __pbn__Background ?? "";
            set => __pbn__Background = value;
        }
        public bool ShouldSerializeBackground() => __pbn__Background != null;
        public void ResetBackground() => __pbn__Background = null;
        private string __pbn__Background;

        [global::ProtoBuf.ProtoContract()]
        public partial class Monument : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
            public string Name { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"x", IsRequired = true)]
            public float X { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"y", IsRequired = true)]
            public float Y { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppEntityInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public AppEntityType Type { get; set; } = AppEntityType.Switch;

        [global::ProtoBuf.ProtoMember(3, Name = @"payload", IsRequired = true)]
        public AppEntityPayload Payload { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppEntityPayload : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"value")]
        public bool Value
        {
            get => __pbn__Value.GetValueOrDefault();
            set => __pbn__Value = value;
        }
        public bool ShouldSerializeValue() => __pbn__Value != null;
        public void ResetValue() => __pbn__Value = null;
        private bool? __pbn__Value;

        [global::ProtoBuf.ProtoMember(2, Name = @"items")]
        public global::System.Collections.Generic.List<Item> Items { get; } = new global::System.Collections.Generic.List<Item>();

        [global::ProtoBuf.ProtoMember(3, Name = @"capacity")]
        public int Capacity
        {
            get => __pbn__Capacity.GetValueOrDefault();
            set => __pbn__Capacity = value;
        }
        public bool ShouldSerializeCapacity() => __pbn__Capacity != null;
        public void ResetCapacity() => __pbn__Capacity = null;
        private int? __pbn__Capacity;

        [global::ProtoBuf.ProtoMember(4, Name = @"has_protection")]
        public bool HasProtection
        {
            get => __pbn__HasProtection.GetValueOrDefault();
            set => __pbn__HasProtection = value;
        }
        public bool ShouldSerializeHasProtection() => __pbn__HasProtection != null;
        public void ResetHasProtection() => __pbn__HasProtection = null;
        private bool? __pbn__HasProtection;

        [global::ProtoBuf.ProtoMember(5, Name = @"protection_expiry")]
        public uint ProtectionExpiry
        {
            get => __pbn__ProtectionExpiry.GetValueOrDefault();
            set => __pbn__ProtectionExpiry = value;
        }
        public bool ShouldSerializeProtectionExpiry() => __pbn__ProtectionExpiry != null;
        public void ResetProtectionExpiry() => __pbn__ProtectionExpiry = null;
        private uint? __pbn__ProtectionExpiry;

        [global::ProtoBuf.ProtoContract()]
        public partial class Item : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"item_id", IsRequired = true)]
            public int ItemId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"quantity", IsRequired = true)]
            public int Quantity { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"item_is_blueprint", IsRequired = true)]
            public bool ItemIsBlueprint { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppTeamInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"leader_steam_id", IsRequired = true)]
        public ulong LeaderSteamId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"members")]
        public global::System.Collections.Generic.List<Member> Members { get; } = new global::System.Collections.Generic.List<Member>();

        [global::ProtoBuf.ProtoMember(3, Name = @"map_notes")]
        public global::System.Collections.Generic.List<Note> MapNotes { get; } = new global::System.Collections.Generic.List<Note>();

        [global::ProtoBuf.ProtoMember(4, Name = @"leader_map_notes")]
        public global::System.Collections.Generic.List<Note> LeaderMapNotes { get; } = new global::System.Collections.Generic.List<Note>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Member : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"steam_id", IsRequired = true)]
            public ulong SteamId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"name", IsRequired = true)]
            public string Name { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"x", IsRequired = true)]
            public float X { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"y", IsRequired = true)]
            public float Y { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"is_online", IsRequired = true)]
            public bool IsOnline { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"spawn_time", IsRequired = true)]
            public uint SpawnTime { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"is_alive", IsRequired = true)]
            public bool IsAlive { get; set; }

            [global::ProtoBuf.ProtoMember(8, Name = @"death_time", IsRequired = true)]
            public uint DeathTime { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Note : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(2, Name = @"type", IsRequired = true)]
            public int Type { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"x", IsRequired = true)]
            public float X { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"y", IsRequired = true)]
            public float Y { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"icon", IsRequired = true)]
            public IconType Icon { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"colour", IsRequired = true)]
            public IconColor Colour { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Name
            {
                get => __pbn__Name ?? "";
                set => __pbn__Name = value;
            }
            public bool ShouldSerializeName() => __pbn__Name != null;
            public void ResetName() => __pbn__Name = null;
            private string __pbn__Name;

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppTeamMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"steam_id", IsRequired = true)]
        public ulong SteamId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"message", IsRequired = true)]
        public string Message { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"color", IsRequired = true)]
        public string Color { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"time", IsRequired = true)]
        public uint Time { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppTeamChat : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"messages")]
        public global::System.Collections.Generic.List<AppTeamMessage> Messages { get; } = new global::System.Collections.Generic.List<AppTeamMessage>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppMarker : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"type", IsRequired = true)]
        public AppMarkerType Type { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"x", IsRequired = true)]
        public float X { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"y", IsRequired = true)]
        public float Y { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"steam_id")]
        public ulong SteamId
        {
            get => __pbn__SteamId.GetValueOrDefault();
            set => __pbn__SteamId = value;
        }
        public bool ShouldSerializeSteamId() => __pbn__SteamId != null;
        public void ResetSteamId() => __pbn__SteamId = null;
        private ulong? __pbn__SteamId;

        [global::ProtoBuf.ProtoMember(6, Name = @"rotation")]
        public float Rotation
        {
            get => __pbn__Rotation.GetValueOrDefault();
            set => __pbn__Rotation = value;
        }
        public bool ShouldSerializeRotation() => __pbn__Rotation != null;
        public void ResetRotation() => __pbn__Rotation = null;
        private float? __pbn__Rotation;

        [global::ProtoBuf.ProtoMember(7, Name = @"radius")]
        public float Radius
        {
            get => __pbn__Radius.GetValueOrDefault();
            set => __pbn__Radius = value;
        }
        public bool ShouldSerializeRadius() => __pbn__Radius != null;
        public void ResetRadius() => __pbn__Radius = null;
        private float? __pbn__Radius;

        [global::ProtoBuf.ProtoMember(8, Name = @"color1")]
        public Vector4 Color1 { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"color2")]
        public Vector4 Color2 { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"alpha")]
        public float Alpha
        {
            get => __pbn__Alpha.GetValueOrDefault();
            set => __pbn__Alpha = value;
        }
        public bool ShouldSerializeAlpha() => __pbn__Alpha != null;
        public void ResetAlpha() => __pbn__Alpha = null;
        private float? __pbn__Alpha;

        [global::ProtoBuf.ProtoMember(11, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get => __pbn__Name ?? "";
            set => __pbn__Name = value;
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(12, Name = @"out_of_stock")]
        public bool OutOfStock
        {
            get => __pbn__OutOfStock.GetValueOrDefault();
            set => __pbn__OutOfStock = value;
        }
        public bool ShouldSerializeOutOfStock() => __pbn__OutOfStock != null;
        public void ResetOutOfStock() => __pbn__OutOfStock = null;
        private bool? __pbn__OutOfStock;

        [global::ProtoBuf.ProtoMember(13, Name = @"sell_orders")]
        public global::System.Collections.Generic.List<SellOrder> SellOrders { get; } = new global::System.Collections.Generic.List<SellOrder>();

        [global::ProtoBuf.ProtoContract()]
        public partial class SellOrder : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"item_id", IsRequired = true)]
            public int ItemId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"quantity", IsRequired = true)]
            public int Quantity { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"currency_id", IsRequired = true)]
            public int CurrencyId { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"cost_per_item", IsRequired = true)]
            public int CostPerItem { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"amount_in_stock", IsRequired = true)]
            public int AmountInStock { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"item_is_blueprint", IsRequired = true)]
            public bool ItemIsBlueprint { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"currency_is_blueprint", IsRequired = true)]
            public bool CurrencyIsBlueprint { get; set; }

            [global::ProtoBuf.ProtoMember(8, Name = @"item_condition")]
            public float ItemCondition
            {
                get => __pbn__ItemCondition.GetValueOrDefault();
                set => __pbn__ItemCondition = value;
            }
            public bool ShouldSerializeItemCondition() => __pbn__ItemCondition != null;
            public void ResetItemCondition() => __pbn__ItemCondition = null;
            private float? __pbn__ItemCondition;

            [global::ProtoBuf.ProtoMember(9, Name = @"item_condition_max")]
            public float ItemConditionMax
            {
                get => __pbn__ItemConditionMax.GetValueOrDefault();
                set => __pbn__ItemConditionMax = value;
            }
            public bool ShouldSerializeItemConditionMax() => __pbn__ItemConditionMax != null;
            public void ResetItemConditionMax() => __pbn__ItemConditionMax = null;
            private float? __pbn__ItemConditionMax;

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppMapMarkers : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"markers")]
        public global::System.Collections.Generic.List<AppMarker> Markers { get; } = new global::System.Collections.Generic.List<AppMarker>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppClanInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"clan_info")]
        public ClanInfo ClanInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppClanMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"steam_id", IsRequired = true)]
        public ulong SteamId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"message", IsRequired = true)]
        public string Message { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"time", IsRequired = true)]
        public long Time { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppClanChat : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"messages")]
        public global::System.Collections.Generic.List<AppClanMessage> Messages { get; } = new global::System.Collections.Generic.List<AppClanMessage>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppNexusAuth : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"server_id", IsRequired = true)]
        public string ServerId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"player_token", IsRequired = true)]
        public int PlayerToken { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppTeamChanged : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"player_id", IsRequired = true)]
        public ulong PlayerId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"team_info", IsRequired = true)]
        public AppTeamInfo TeamInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppNewTeamMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"message", IsRequired = true)]
        public AppTeamMessage Message { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppEntityChanged : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"entity_id", IsRequired = true)]
        public uint EntityId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"payload", IsRequired = true)]
        public AppEntityPayload Payload { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppClanChanged : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"clan_info")]
        public ClanInfo ClanInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppNewClanMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"clan_id", IsRequired = true)]
        public long ClanId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"message", IsRequired = true)]
        public AppClanMessage Message { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppCameraSubscribe : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"camera_id", IsRequired = true)]
        public string CameraId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppCameraInput : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"buttons", IsRequired = true)]
        public int Buttons { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"mouse_delta", IsRequired = true)]
        public Vector2 MouseDelta { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppCameraInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"width", IsRequired = true)]
        public int Width { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"height", IsRequired = true)]
        public int Height { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"near_plane", IsRequired = true)]
        public float NearPlane { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"far_plane", IsRequired = true)]
        public float FarPlane { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"control_flags", IsRequired = true)]
        public int ControlFlags { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AppCameraRays : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"vertical_fov", IsRequired = true)]
        public float VerticalFov { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"sample_offset", IsRequired = true)]
        public int SampleOffset { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"ray_data", IsRequired = true)]
        public byte[] RayData { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"distance", IsRequired = true)]
        public float Distance { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"entities")]
        public global::System.Collections.Generic.List<Entity> Entities { get; } = new global::System.Collections.Generic.List<Entity>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Entity : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"entity_id", IsRequired = true)]
            public uint EntityId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"type", IsRequired = true)]
            public AppCameraRays.EntityType Type { get; set; } = AppCameraRays.EntityType.Tree;

            [global::ProtoBuf.ProtoMember(3, Name = @"position", IsRequired = true)]
            public Vector3 Position { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"rotation", IsRequired = true)]
            public Vector3 Rotation { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"size", IsRequired = true)]
            public Vector3 Size { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Name
            {
                get => __pbn__Name ?? "";
                set => __pbn__Name = value;
            }
            public bool ShouldSerializeName() => __pbn__Name != null;
            public void ResetName() => __pbn__Name = null;
            private string __pbn__Name;

        }

        [global::ProtoBuf.ProtoContract()]
        public enum EntityType
        {
            Tree = 1,
            Player = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum AppEntityType
    {
        Switch = 1,
        Alarm = 2,
        StorageMonitor = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum IconType
    {
        Default = 0,
        Money = 1,
        Home = 2,
        Drop = 3,
        Sight = 4,
        Shield = 5,
        Skull = 6,
        Bed = 7,
        Sleep = 8,
        Gun = 9,
        Rock = 10,
        Chest = 11,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum IconColor
    {
        Yellow = 0,
        Blue = 1,
        Green = 2,
        Red = 3,
        Purple = 4,
        Cyan = 5,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum AppMarkerType
    {
        Unknow = 0,
        Player = 1,
        Explosion = 2,
        VendingMachine = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"CH47")]
        Ch47 = 4,
        CargoShip = 5,
        Crate = 6,
        GenericRadius = 7,
        PatrolHelicopter = 8,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
