// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace AndroidCheckinProto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ChromeBuildProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(Platform.PlatformWin)]
        public Platform platform
        {
            get => __pbn__platform ?? Platform.PlatformWin;
            set => __pbn__platform = value;
        }
        public bool ShouldSerializeplatform() => __pbn__platform != null;
        public void Resetplatform() => __pbn__platform = null;
        private Platform? __pbn__platform;

        [global::ProtoBuf.ProtoMember(2, Name = @"chrome_version")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ChromeVersion
        {
            get => __pbn__ChromeVersion ?? "";
            set => __pbn__ChromeVersion = value;
        }
        public bool ShouldSerializeChromeVersion() => __pbn__ChromeVersion != null;
        public void ResetChromeVersion() => __pbn__ChromeVersion = null;
        private string __pbn__ChromeVersion;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(Channel.ChannelStable)]
        public Channel channel
        {
            get => __pbn__channel ?? Channel.ChannelStable;
            set => __pbn__channel = value;
        }
        public bool ShouldSerializechannel() => __pbn__channel != null;
        public void Resetchannel() => __pbn__channel = null;
        private Channel? __pbn__channel;

        [global::ProtoBuf.ProtoContract()]
        public enum Platform
        {
            [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_WIN")]
            PlatformWin = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_MAC")]
            PlatformMac = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_LINUX")]
            PlatformLinux = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_CROS")]
            PlatformCros = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_IOS")]
            PlatformIos = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_ANDROID")]
            PlatformAndroid = 6,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum Channel
        {
            [global::ProtoBuf.ProtoEnum(Name = @"CHANNEL_STABLE")]
            ChannelStable = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"CHANNEL_BETA")]
            ChannelBeta = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"CHANNEL_DEV")]
            ChannelDev = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"CHANNEL_CANARY")]
            ChannelCanary = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"CHANNEL_UNKNOWN")]
            ChannelUnknown = 5,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AndroidCheckinProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"last_checkin_msec")]
        public long LastCheckinMsec
        {
            get => __pbn__LastCheckinMsec.GetValueOrDefault();
            set => __pbn__LastCheckinMsec = value;
        }
        public bool ShouldSerializeLastCheckinMsec() => __pbn__LastCheckinMsec != null;
        public void ResetLastCheckinMsec() => __pbn__LastCheckinMsec = null;
        private long? __pbn__LastCheckinMsec;

        [global::ProtoBuf.ProtoMember(6, Name = @"cell_operator")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CellOperator
        {
            get => __pbn__CellOperator ?? "";
            set => __pbn__CellOperator = value;
        }
        public bool ShouldSerializeCellOperator() => __pbn__CellOperator != null;
        public void ResetCellOperator() => __pbn__CellOperator = null;
        private string __pbn__CellOperator;

        [global::ProtoBuf.ProtoMember(7, Name = @"sim_operator")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SimOperator
        {
            get => __pbn__SimOperator ?? "";
            set => __pbn__SimOperator = value;
        }
        public bool ShouldSerializeSimOperator() => __pbn__SimOperator != null;
        public void ResetSimOperator() => __pbn__SimOperator = null;
        private string __pbn__SimOperator;

        [global::ProtoBuf.ProtoMember(8, Name = @"roaming")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Roaming
        {
            get => __pbn__Roaming ?? "";
            set => __pbn__Roaming = value;
        }
        public bool ShouldSerializeRoaming() => __pbn__Roaming != null;
        public void ResetRoaming() => __pbn__Roaming = null;
        private string __pbn__Roaming;

        [global::ProtoBuf.ProtoMember(9, Name = @"user_number")]
        public int UserNumber
        {
            get => __pbn__UserNumber.GetValueOrDefault();
            set => __pbn__UserNumber = value;
        }
        public bool ShouldSerializeUserNumber() => __pbn__UserNumber != null;
        public void ResetUserNumber() => __pbn__UserNumber = null;
        private int? __pbn__UserNumber;

        [global::ProtoBuf.ProtoMember(12, Name = @"type")]
        [global::System.ComponentModel.DefaultValue(DeviceType.DeviceAndroidOs)]
        public DeviceType Type
        {
            get => __pbn__Type ?? DeviceType.DeviceAndroidOs;
            set => __pbn__Type = value;
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private DeviceType? __pbn__Type;

        [global::ProtoBuf.ProtoMember(13, Name = @"chrome_build")]
        public ChromeBuildProto ChromeBuild { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum DeviceType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"DEVICE_ANDROID_OS")]
        DeviceAndroidOs = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"DEVICE_IOS_OS")]
        DeviceIosOs = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"DEVICE_CHROME_BROWSER")]
        DeviceChromeBrowser = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"DEVICE_CHROME_OS")]
        DeviceChromeOs = 4,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
