// This file needs to be changed
// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace CheckinProto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GservicesSetting : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
        public byte[] Name { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"value", IsRequired = true)]
        public byte[] Value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AndroidCheckinRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"imei")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Imei
        {
            get => __pbn__Imei ?? "";
            set => __pbn__Imei = value;
        }
        public bool ShouldSerializeImei() => __pbn__Imei != null;
        public void ResetImei() => __pbn__Imei = null;
        private string __pbn__Imei;

        [global::ProtoBuf.ProtoMember(10, Name = @"meid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Meid
        {
            get => __pbn__Meid ?? "";
            set => __pbn__Meid = value;
        }
        public bool ShouldSerializeMeid() => __pbn__Meid != null;
        public void ResetMeid() => __pbn__Meid = null;
        private string __pbn__Meid;

        [global::ProtoBuf.ProtoMember(9, Name = @"mac_addr")]
        public global::System.Collections.Generic.List<string> MacAddrs { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(19, Name = @"mac_addr_type")]
        public global::System.Collections.Generic.List<string> MacAddrTypes { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(16, Name = @"serial_number")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SerialNumber
        {
            get => __pbn__SerialNumber ?? "";
            set => __pbn__SerialNumber = value;
        }
        public bool ShouldSerializeSerialNumber() => __pbn__SerialNumber != null;
        public void ResetSerialNumber() => __pbn__SerialNumber = null;
        private string __pbn__SerialNumber;

        [global::ProtoBuf.ProtoMember(17, Name = @"esn")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Esn
        {
            get => __pbn__Esn ?? "";
            set => __pbn__Esn = value;
        }
        public bool ShouldSerializeEsn() => __pbn__Esn != null;
        public void ResetEsn() => __pbn__Esn = null;
        private string __pbn__Esn;

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public long Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private long? __pbn__Id;

        [global::ProtoBuf.ProtoMember(7, Name = @"logging_id")]
        public long LoggingId
        {
            get => __pbn__LoggingId.GetValueOrDefault();
            set => __pbn__LoggingId = value;
        }
        public bool ShouldSerializeLoggingId() => __pbn__LoggingId != null;
        public void ResetLoggingId() => __pbn__LoggingId = null;
        private long? __pbn__LoggingId;

        [global::ProtoBuf.ProtoMember(3, Name = @"digest")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Digest
        {
            get => __pbn__Digest ?? "";
            set => __pbn__Digest = value;
        }
        public bool ShouldSerializeDigest() => __pbn__Digest != null;
        public void ResetDigest() => __pbn__Digest = null;
        private string __pbn__Digest;

        [global::ProtoBuf.ProtoMember(6, Name = @"locale")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Locale
        {
            get => __pbn__Locale ?? "";
            set => __pbn__Locale = value;
        }
        public bool ShouldSerializeLocale() => __pbn__Locale != null;
        public void ResetLocale() => __pbn__Locale = null;
        private string __pbn__Locale;

        [global::ProtoBuf.ProtoMember(4, Name = @"checkin", IsRequired = true)]
        public AndroidCheckinProto.AndroidCheckinProto Checkin { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"desired_build")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DesiredBuild
        {
            get => __pbn__DesiredBuild ?? "";
            set => __pbn__DesiredBuild = value;
        }
        public bool ShouldSerializeDesiredBuild() => __pbn__DesiredBuild != null;
        public void ResetDesiredBuild() => __pbn__DesiredBuild = null;
        private string __pbn__DesiredBuild;

        [global::ProtoBuf.ProtoMember(8, Name = @"market_checkin")]
        [global::System.ComponentModel.DefaultValue("")]
        public string MarketCheckin
        {
            get => __pbn__MarketCheckin ?? "";
            set => __pbn__MarketCheckin = value;
        }
        public bool ShouldSerializeMarketCheckin() => __pbn__MarketCheckin != null;
        public void ResetMarketCheckin() => __pbn__MarketCheckin = null;
        private string __pbn__MarketCheckin;

        [global::ProtoBuf.ProtoMember(11, Name = @"account_cookie")]
        public global::System.Collections.Generic.List<string> AccountCookies { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(12, Name = @"time_zone")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TimeZone
        {
            get => __pbn__TimeZone ?? "";
            set => __pbn__TimeZone = value;
        }
        public bool ShouldSerializeTimeZone() => __pbn__TimeZone != null;
        public void ResetTimeZone() => __pbn__TimeZone = null;
        private string __pbn__TimeZone;

        [global::ProtoBuf.ProtoMember(13, Name = @"security_token", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong SecurityToken
        {
            get => __pbn__SecurityToken.GetValueOrDefault();
            set => __pbn__SecurityToken = value;
        }
        public bool ShouldSerializeSecurityToken() => __pbn__SecurityToken != null;
        public void ResetSecurityToken() => __pbn__SecurityToken = null;
        private ulong? __pbn__SecurityToken;

        [global::ProtoBuf.ProtoMember(14, Name = @"version")]
        public int Version
        {
            get => __pbn__Version.GetValueOrDefault();
            set => __pbn__Version = value;
        }
        public bool ShouldSerializeVersion() => __pbn__Version != null;
        public void ResetVersion() => __pbn__Version = null;
        private int? __pbn__Version;

        [global::ProtoBuf.ProtoMember(15, Name = @"ota_cert")]
        public global::System.Collections.Generic.List<string> OtaCerts { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(20, Name = @"fragment")]
        public int Fragment
        {
            get => __pbn__Fragment.GetValueOrDefault();
            set => __pbn__Fragment = value;
        }
        public bool ShouldSerializeFragment() => __pbn__Fragment != null;
        public void ResetFragment() => __pbn__Fragment = null;
        private int? __pbn__Fragment;

        [global::ProtoBuf.ProtoMember(21, Name = @"user_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string UserName
        {
            get => __pbn__UserName ?? "";
            set => __pbn__UserName = value;
        }
        public bool ShouldSerializeUserName() => __pbn__UserName != null;
        public void ResetUserName() => __pbn__UserName = null;
        private string __pbn__UserName;

        [global::ProtoBuf.ProtoMember(22, Name = @"user_serial_number")]
        public int UserSerialNumber
        {
            get => __pbn__UserSerialNumber.GetValueOrDefault();
            set => __pbn__UserSerialNumber = value;
        }
        public bool ShouldSerializeUserSerialNumber() => __pbn__UserSerialNumber != null;
        public void ResetUserSerialNumber() => __pbn__UserSerialNumber = null;
        private int? __pbn__UserSerialNumber;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AndroidCheckinResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"stats_ok", IsRequired = true)]
        public bool StatsOk { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"time_msec")]
        public long TimeMsec
        {
            get => __pbn__TimeMsec.GetValueOrDefault();
            set => __pbn__TimeMsec = value;
        }
        public bool ShouldSerializeTimeMsec() => __pbn__TimeMsec != null;
        public void ResetTimeMsec() => __pbn__TimeMsec = null;
        private long? __pbn__TimeMsec;

        [global::ProtoBuf.ProtoMember(4, Name = @"digest")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Digest
        {
            get => __pbn__Digest ?? "";
            set => __pbn__Digest = value;
        }
        public bool ShouldSerializeDigest() => __pbn__Digest != null;
        public void ResetDigest() => __pbn__Digest = null;
        private string __pbn__Digest;

        [global::ProtoBuf.ProtoMember(9, Name = @"settings_diff")]
        public bool SettingsDiff
        {
            get => __pbn__SettingsDiff.GetValueOrDefault();
            set => __pbn__SettingsDiff = value;
        }
        public bool ShouldSerializeSettingsDiff() => __pbn__SettingsDiff != null;
        public void ResetSettingsDiff() => __pbn__SettingsDiff = null;
        private bool? __pbn__SettingsDiff;

        [global::ProtoBuf.ProtoMember(10, Name = @"delete_setting")]
        public global::System.Collections.Generic.List<string> DeleteSettings { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(5, Name = @"setting")]
        public global::System.Collections.Generic.List<GservicesSetting> Settings { get; } = new global::System.Collections.Generic.List<GservicesSetting>();

        [global::ProtoBuf.ProtoMember(6, Name = @"market_ok")]
        public bool MarketOk
        {
            get => __pbn__MarketOk.GetValueOrDefault();
            set => __pbn__MarketOk = value;
        }
        public bool ShouldSerializeMarketOk() => __pbn__MarketOk != null;
        public void ResetMarketOk() => __pbn__MarketOk = null;
        private bool? __pbn__MarketOk;

        [global::ProtoBuf.ProtoMember(7, Name = @"android_id", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong AndroidId
        {
            get => __pbn__AndroidId.GetValueOrDefault();
            set => __pbn__AndroidId = value;
        }
        public bool ShouldSerializeAndroidId() => __pbn__AndroidId != null;
        public void ResetAndroidId() => __pbn__AndroidId = null;
        private ulong? __pbn__AndroidId;

        [global::ProtoBuf.ProtoMember(8, Name = @"security_token", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong SecurityToken
        {
            get => __pbn__SecurityToken.GetValueOrDefault();
            set => __pbn__SecurityToken = value;
        }
        public bool ShouldSerializeSecurityToken() => __pbn__SecurityToken != null;
        public void ResetSecurityToken() => __pbn__SecurityToken = null;
        private ulong? __pbn__SecurityToken;

        [global::ProtoBuf.ProtoMember(11, Name = @"version_info")]
        [global::System.ComponentModel.DefaultValue("")]
        public string VersionInfo
        {
            get => __pbn__VersionInfo ?? "";
            set => __pbn__VersionInfo = value;
        }
        public bool ShouldSerializeVersionInfo() => __pbn__VersionInfo != null;
        public void ResetVersionInfo() => __pbn__VersionInfo = null;
        private string __pbn__VersionInfo;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
